from services.userAuthFile import *
from services.productFile import *
from services.categoryFile import *
from services.articleFile import *
from services.filterFile import *
from services.classifierFile import *
from services.cartFile import *
from services.orderFile import *
from services.feedbackFile import *
from services.vacancyFile import *
from services.deliveryFile import *
from services.contactsFile import *
from services.ourshopsFile import *
