from schemas.userAuthFile import *
from schemas.productFile import *
from schemas.categoryFile import *
from schemas.articleFile import *
from schemas.orderFile import *
from schemas.defaultFile import *
from schemas.classifierFile import *
from schemas.cartFile import *
from schemas.feedbackFile import *
